// Generated BeanShell Script
// Source: Main.java
// DO NOT EDIT THIS FILE DIRECTLY

load(appPath + "/utils/MessageHandler.java");
load(appPath + "/utils/Helper.java");
load(appPath + "/constants/MessageType.java");
load(appPath + "/enums/ChatType.java");

// Callback methods - will be extracted to root level in BeanShell
public void onMsg(Object msg) {
    // Now you have full IDE hints!
    String text = msg.MessageContent;
    String qq = msg.UserUin;
    String qun = msg.GroupUin;
    boolean isGroup = msg.IsGroup;
    if ("菜单".equals(text) && qq.equals(myUin)) {
        String reply = "TG频道：https://t.me/QStoryPlugin\n交流群:979938489\n---------\n这是菜单 你可以发送下面的指令来进行测试  \n艾特我\n回复我\n私聊我";
        if (isGroup) {
            sendMsg(qun, "", reply);
        } else {
            sendMsg("", qq, reply);
        }
    }
    if ("艾特我".equals(text) && isGroup && qq.equals(myUin)) {
        sendMsg(qun, "", "[AtQQ=" + qq + "] 嗯呐");
    }
    if ("回复我".equals(text) && isGroup && qq.equals(myUin)) {
        sendReply(qun, msg, "好啦");
    }
    if ("私聊我".equals(text)) {
        sendMsg(qun, qq, "我已经私聊你咯");
    }
    if ("回表情".equals(text)) {
        replyEmoji(msg, "1");
    }
    // 测试新增的工具方法
    if (containsKeyword(text, "测试")) {
        toast("检测到关键词:测试");
    }
    // 使用模块方法处理禁言命令
    if (isMuteCommand(msg)) {
        int banTime = parseTimeBymessage(msg);
        if (banTime >= 60 * 60 * 24 * 30 + 1) {
            sendMsg(msg.GroupUin, "", "请控制在30天以内");
            return;
        } else {
            for (String atUin : msg.mAtList) {
                forbidden(msg.GroupUin, atUin, banTime);
            }
        }
    }
}

public void onCreateMenu(Object msg) {
    if (msg.IsGroup) {
        addMenuItem("仅群", "showGroup");
        addMenuItem("保存", "saveVoice");
    }
}

// Custom menu callback
public void showGroup(Object msg) {
    toast("提示在" + msg.MessageType);
}

// Custom menu callback
public void saveVoice(Object msg) {
    toast("" + MessageType.VOICE);
    if (msg.MessageType == MessageType.VOICE) {
        toast(msg.LocalPath);
    }
}

// Floating window menu callback - parameters: groupUin, uin, chatType
public void 加载提示(String groupUin, String uin, int chatType) {
    if (getString("加载提示", "开关") == null) {
        putString("加载提示", "开关", "关");
        toast("已关闭加载提示");
    } else {
        putString("加载提示", "开关", null);
        toast("已开启加载提示");
    }
}

addItem("开关加载提示", "加载提示");
if (getString("加载提示", "开关") == null) {
    toast("发送 \"菜单\" 查看使用说明");
}

