// Generated BeanShell Script
// Source: constants\MessageType.java
// DO NOT EDIT THIS FILE DIRECTLY

if (Constants_MessageType == void) {
    class Constants_MessageType {
        TEXT_OR_IMAGE = 1;
        CARD = 2;
        MIXED_MEDIA = 3;
        VOICE = 4;
        FILE = 5;
        REPLY = 6;
    }
}
// 别名,保持原类名可访问
MessageType = Constants_MessageType;
